//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JokeBox.Core.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JokeBox.Core.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Jokebox.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        public static string Bewerten {
            get {
                return ResourceManager.GetString("Bewerten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string Buchstaben {
            get {
                return ResourceManager.GetString("Buchstaben", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        public static string CCode {
            get {
                return ResourceManager.GetString("CCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to So you never get bored.
        /// </summary>
        public static string Descr {
            get {
                return ResourceManager.GetString("Descr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One moment.
        /// </summary>
        public static string EinenMoment {
            get {
                return ResourceManager.GetString("EinenMoment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developed by Areon.
        /// </summary>
        public static string EntwickeltVonAreon {
            get {
                return ResourceManager.GetString("EntwickeltVonAreon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tell a joke.
        /// </summary>
        public static string Erzaehlen {
            get {
                return ResourceManager.GetString("Erzaehlen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to favorite.
        /// </summary>
        public static string Favorit {
            get {
                return ResourceManager.GetString("Favorit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get unlimited version.
        /// </summary>
        public static string GetUnlimited {
            get {
                return ResourceManager.GetString("GetUnlimited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Hochladen {
            get {
                return ResourceManager.GetString("Hochladen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You exceeded the limited version of 50 Jokes per day. But no worries, there&apos;s an unlimited version waiting for you :).
        /// </summary>
        public static string LimitExceeded {
            get {
                return ResourceManager.GetString("LimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail.
        /// </summary>
        public static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My favorites.
        /// </summary>
        public static string MeineFavs {
            get {
                return ResourceManager.GetString("MeineFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to newest.
        /// </summary>
        public static string Neuste {
            get {
                return ResourceManager.GetString("Neuste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters left:.
        /// </summary>
        public static string NochMindestens {
            get {
                return ResourceManager.GetString("NochMindestens", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t saved any favorites.
        /// </summary>
        public static string NoFavs {
            get {
                return ResourceManager.GetString("NoFavs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report joke.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have Jokebox for a long time now and we are happy to see you enjoying it. Now we would like to read your review.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Before submitting jokes, you need to have your unique and unchangeable name. With your unique name you can collect and track your points. One upvote stands for one point..
        /// </summary>
        public static string SetName {
            get {
                return ResourceManager.GetString("SetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Speichern {
            get {
                return ResourceManager.GetString("Speichern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to share.
        /// </summary>
        public static string Teilen {
            get {
                return ResourceManager.GetString("Teilen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too short.
        /// </summary>
        public static string ZuKurz {
            get {
                return ResourceManager.GetString("ZuKurz", resourceCulture);
            }
        }
    }
}
